version: '3.8'
services:
  web:
    build:
      context: ./docker/web
      dockerfile: Dockerfile
    ports:
      - "8000:80"
    volumes:
      - ./src:/var/www/html
      - ./docker/web/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - app
      - db
    networks:
      - app_net

  app:
    build:
      context: ./docker/app
      dockerfile: Dockerfile
    volumes:
      - ./src:/var/www/html
    networks:
      - app_net


  db:
    image: mysql:5.7
    env_file:
      - ./env/mysql.env
    networks:
      - app_net

  composer:
    build:
      context: ./docker/composer
      dockerfile: Dockerfile
    volumes:
      - ./src:/var/www/html
    working_dir: /var/www/html 

networks:
  app_net:

volumes:
  db_data:
